name: MobStacker
main: UnknownOre\MobStacker\Main
version: 0.2.0
api: 3.8.1
load: POSTWORLD
author: UnknownOre
description: a super simple but highly effective plugin designed to reduce lag both for the server and clients.
website: https://github.com/UnknownOre
